name: Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/EvidiAS.SecureDevelopment/**'
      - 'test/EvidiAS.SecureDevelopment.UnitTests/**'
    branches:
      - 'main'
      - 'feature/**'
  push:
    paths:
      - 'src/EvidiAS.SecureDevelopment/**'
      - 'test/EvidiAS.SecureDevelopment.UnitTests/**'
    branches:
      - 'main'

env:
  ARTIFACT_NAME: EvidiAS.SecureDevelopment-CI
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
  PROJECT_DIRECTORY: src/EvidiAS.SecureDevelopment
  TEST_DIRECTORY: test/EvidiAS.SecureDevelopment.UnitTests
  PROJECT_NAME: EvidiAS.SecureDevelopment.csproj

jobs:
  build:
    name: Build & Test a .NET Project
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIRECTORY }} 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.TEST_DIRECTORY }}

