name: Build

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/EvidiAS.SecureDevelopment/**'
      - 'test/EvidiAS.SecureDevelopment.UnitTests/**'
    branches:
      - 'main'
      - 'feature/**'
  push:
    paths:
      - 'src/EvidiAS.SecureDevelopment/**'
      - 'test/EvidiAS.SecureDevelopment.UnitTests/**'
    branches:
      - 'main'
      - 'feature/**'

env:
  ARTIFACT_NAME: EvidiAS.SecureDevelopment-CI
  CONFIGURATION: Release
  DOTNET_VERSION: 7.0.x
  PROJECT_DIRECTORY: src/EvidiAS.SecureDevelopment
  TEST_DIRECTORY: test/EvidiAS.SecureDevelopment.UnitTests
  PROJECT_NAME: EvidiAS.SecureDevelopment.csproj

jobs:
  build:
    name: Build, Test & Publish a .NET Artifact
    defaults:
      run:
        working-directory: ${{ env.PROJECT_DIRECTORY }} 
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]

    steps:
    - uses: actions/checkout@v3

    # CodeQL requires that the build process occurs between CodeQL initialise and analysis
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }} 
    
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }}

    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.TEST_DIRECTORY }}
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"
    
    - name: Publish
      run: |
        dotnet publish --no-build --configuration ${{ env.CONFIGURATION }} --output ./publish
        cd publish
        zip -r ../${{ env.ARTIFACT_NAME }}.zip .

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: ${{ env.PROJECT_DIRECTORY }}/${{ env.ARTIFACT_NAME }}.zip
        if-no-files-found: error

  deploy:
    name: Deploy Azure Web App
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}

      - name: Unzip Build Artifact
        run: |
          unzip ${{ env.ARTIFACT_NAME }}.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'secure-code-wa'
          slot-name: 'production'
          publish-profile: ${{ secrets.WebAppPublishProfile }}
          package: .
      
      - name: OWASP DAST
        uses: zaproxy/action-api-scan@v0.2.0
        with:
          target: ${{ steps.deploy-to-webapp.outputs.webapp-url }}/swagger/v1/swagger.json
          token: ${{ secrets.GITHUB_TOKEN }}
          issue_title: DAST Results
